spring:
  datasource:
    url: jdbc:mariadb://172.30.1.18:3306/reservationservice
    driver-class-name: org.mariadb.jdbc.Driver
    username: reservationuser
    password: a1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LXJlc2VydmF0aW9uLXByb2plY3Qtand0LXNlY3JldC10b2tlbgo

